[package]
name = "nm_plugin"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
log = { workspace = true }
env_logger = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
nm = { "path" = "../libnm" }
nmstate = { "path" = "../nmstate" }

[lib]
name = "nm_plugin"
path = "lib.rs"
